import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import LocaleProvider from "./LocaleProvider";
import { ClerkProvider } from "@clerk/nextjs";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

type Props = {
  children: React.ReactNode;
};

export default async function RootLayout({ children }: Props) {
  return (
    <ClerkProvider>
      <html className={`${geist.variable}`}>
        <body>
          <LocaleProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </LocaleProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
